@startuml actuator_class_diagram
skinparam {
    defaultFontName Ricty Diminished
    monochrome true
}

package Golem {
    interface Component

    folder actuators {
        interface Actuator {
            + Delete(Component*)
            + Id(Component): int
            + Tag(Component): const char*
            + State(Component): const char*
            + IsOff(Component): bool
            + TurnOn(Component)
            + TurnOff(Component)
            + ForceTurnOff(Component)
        }

        class NullActuator {
            + GetInstance(): Component
        }

        folder motors {
            interface Motor {
                + Delete(Component*)
                + Id(Component): int
                + Tag(Component): const char*
                + State(Component): const char*
                + IsStopped(Component): bool
                + Run(Component)
                + Stop(Component)
                + ForceStop(Component)
                + GetDirection(Component): const char*
                + SetDirection(Component, const char*)
                + GetSpeed(Component): int
                + SetSpeed(Component, int)
            }

            class NullMotor {
                + GetInstance(): Component
            }

            folder pulse_motors {
                interface PulseMotor {
                    + Delete(Component*)
                    + Id(Component): int
                    + Tag(Component): const char*
                    + State(Component): const char*
                    + IsStopped(Component): bool
                    + Run(Component)
                    + Stop(Component)
                    + ForceStop(Component)
                    + GetDirection(Component): const char*
                    + SetDirection(Component, const char*)
                    + GetSpeed(Component): int
                    + SetSpeed(Component, int)
                    + GetMode(Component): const char*
                    + SelectMode(Component, const char*)
                    + GetPulseRate(Component): int
                    + SetPulseRate(Component, int)
                    + GetPosition(Component): int
                }

                class NullPulseMotor {
                    + GetInstance(): Component
                }

                PulseMotor <|-- NullPulseMotor
            }

            Motor <|-- NullMotor
            Motor <|.. PulseMotor
        }

        folder solenids {
            interface Solenoid {
                + Delete(Component*)
                + Id(Component): int
                + Tag(Component): const char*
                + State(Component): const char*
                + IsUnlocked(Component): bool
                + Lock(Component)
                + Unlock(Component)
                + ForceUnlock(Component)
            }

            class NullSolenoid {
                + GetInstance(): Component
            }

            Solenoid <|-- NullSolenoid
        }

        Actuator <|-- NullActuator
        Actuator <|.. Motor
        Actuator <|.. Solenoid
    }

    Component <|.. Actuator
}

@enduml
