@startuml command_class_diagram
skinparam {
    defaultFontName Ricty Diminished
    monochrome true
}

package Golem {
    interface Command {
        + Delete(Command*)
        + Do()
    }

    interface ActiveObjectEngine {
        + Delete(ActiveObjectEngine*)
        + Run(ActiveObjectEngine)
        + AddCommand(ActiveObjectEngine, Command)
    }

    folder commands {
        class SleepCommand {
            + New(int, ActiveObjectEngine, Command): Command
        }

        class ErrorCommand {
            + New(NotifyDelegate): Command
            + SetErrorInfo(Command, const char*, int, int)
        }

        class NullCommand {
            + GetInstance(): Command
        }

        class CountingCommandStub {
            + New(): Command
            + Count(Command): int
        }
    }

    Command <|-- SleepCommand
    Command <|-- ErrorCommand
    Command <|-- NullCommand
    Command <|-- CountingCommandStub
    SleepCommand -> ActiveObjectEngine
}
@enduml
