@startuml component_class_diagram
skinparam {
    defaultFontName Ricty Diminished
    monochrome true
}

package Golem {
        interface Component {
            + Delete(Component*)
            + Id(Component): int
            + Tag(Component): const char*
        }

        interface ComponentFactory {
            + Delete(ComponentFactory*)
            + Make(ComponentFactory, const char*, int): Component
        }
}
@enduml
