@startuml display_class_diagram
skinparam {
    defaultFontName Ricty Diminished
    monochrome true
}

package Golem {
    interface Component

    folder displays {
        interface Display {
            + Delete(Component*)
            + Id(Component): int
            + Tag(Component): const char*
            + State(Component): const char*
            + Reset(Component)
        }

        class NullDisplay {
            + GetInstance(): Component
        }

        folder leds {
            interface Led {
                + Delete(Component*)
                + Id(Component): int
                + Tag(Component): const char*
                + State(Component): const char*
                + TurnOff(Component)
                + TurnOn(Component)
                + IsOff(Component): bool
                + IsOn(Component): bool
            }

            class NullLed {
                + GetInstance(): Component
            }

            folder led_arrays {
                interface LedArray {
                    + Delete(Component*)
                    + Id(Component): int
                    + Tag(Component): const char*
                    + State(Component): const char*
                    + TurnAllOff(Component)
                    + TurnAllOn(Component)
                    + IsAllOff(Component): bool
                    + IsAllOn(Component): bool
                    + TurnOff(Component, int)
                    + TurnOn(Component, int)
                    + IsOff(Component, int): bool
                    + IsOn(Component, int): bool
                }

                class NullLedArray {
                    + GetInstance(): Component
                }

                LedArray <|-- NullLedArray
            }

            Led <|-- NullLed
            Led <|.. LedArray
        }

        folder seven_segment_displays {
            interface SevenSegmentDisplay {
                + Delete(Component*)
                + Id(Component): int
                + Tag(Component): const char*
                + State(Component): const char*
                + Clear(Component)
                + Get(Component): uint8_t
                + Set(Component, uint8_t)
            }

                class NullSevenSegmentDisplay {
                    + GetInstance(): Component
                }

            SevenSegmentDisplay <|-- NullSevenSegmentDisplay
        }

        Display <|-- NullDisplay
        Display <|.. Led
        Display <|.. SevenSegmentDisplay
    }

    Component <|.. Display
}
@enduml
