@startuml display_class_diagram
skinparam {
    defaultFontName Ricty Diminished
    monochrome true
}

package Golem {
    folder displays {
        interface Display {
            + Delete(Display*)
            + GetId(Display): int
            + GetTag(Display): const char*
            + GetState(Display): const char*
            + Reset(Display)
        }

        interface DisplayFactory {
            + Delete(DisplayFactory*)
            + Make(DisplayFactory, int): Display
        }

        folder leds {
            interface Led {
                + Delete(Led*)
                + GetId(Led): int
                + GetTag(Led): const char*
                + GetState(Led): const char*
                + TurnOff(Led)
                + TurnOn(Led)
                + IsOff(Led): bool
                + IsOn(Led): bool
            }

            interface LedFactory {
                + Delete(LedFactory*)
                + Make(LedFactory, int): Led
            }

            folder led_arrays {
                interface LedArray {
                    + Delete(LedArray*)
                    + GetId(LedArray): int
                    + GetTag(LedArray): const char*
                    + GetState(LedArray): const char*
                    + TurnAllOff(LedArray)
                    + TurnAllOn(LedArray)
                    + IsAllOff(LedArray): bool
                    + IsAllOn(LedArray): bool
                    + TurnOff(LedArray, int)
                    + TurnOn(LedArray, int)
                    + IsOff(LedArray, int): bool
                    + IsOn(LedArray, int): bool
                }

                interface LedArrayFactory {
                    + Delete(LedArrayFactory*)
                    + Make(LedArrayFactory, int): LedArray
                }

                LedArray <- LedArrayFactory
            }

            Led <- LedFactory
            Led <|.. LedArray
        }

        folder seven_segment_displays {
            interface SevenSegmentDisplay {
                + Delete(SevenSegmentDisplay*)
                + GetId(SevenSegmentDisplay): int
                + GetTag(SevenSegmentDisplay): const char*
                + GetState(SevenSegmentDisplay): const char*
                + Clear(SevenSegmentDisplay)
                + Get(SevenSegmentDisplay): uint8_t
                + Set(SevenSegmentDisplay, uint8_t)
            }

            interface SevenSegmentDisplayFactory {
                + Delete(SevenSegmentDisplayFactory*)
                + Make(SevenSegmentDisplayFactory, int): SevenSegmentDisplay
            }

            SevenSegmentDisplay <- SevenSegmentDisplayFactory
        }

        Display <- DisplayFactory
        Display <|.. Led
        Display <|.. SevenSegmentDisplay
    }

    Command <|-- Display
}
@enduml
