@startuml sensor_class_diagram
skinparam {
    defaultFontName Ricty Diminished
    monochrome true
}

package Golem {
    interface Command {
        + Delete(Command*)
        + Do()
    }

    folder sensors {
        interface Sensor {
            + Delete(Sensor*)
            + SensorWatchCommand(Sensor, const char*, Command): Command
            + GetId(Sensor): int
            + GetTag(Sensor): const char*
            + GetState(Sensor): const char*
            + IsDefaultState(Sensor): bool
        }

        interface SensorFactory {
            + Delete(SensorFactory*)
            + Make(SensorFactory, int): Sensor
        }

        folder microswitches {
            interface Microswitch {
                + Delete(Microswitch*)
                + SensorWatchCommand(Sensor, const char*, Command): Command
                + GetId(Sensor): int
                + GetTag(Sensor): const char*
                + GetState(Sensor): const char*
                + IsOff(Sensor): bool
                + IsOn(Sensor): bool
            }

            interface MicroswitchFactory {
                + Delete(MicroswitchFactory*)
                + Make(MicroswitchFactory, int): Microswitch
            }

            Microswitch <- MicroswitchFactory
        }

        folder photosensors {
            interface Photosensor {
                + Delete(Photosensor*)
                + SensorWatchCommand(Sensor, const char*, Command): Command
                + GetId(Sensor): int
                + GetTag(Sensor): const char*
                + GetState(Sensor): const char*
                + IsLight(Sensor): bool
                + IsDark(Sensor): bool
            }

            interface PhotosensorFactory {
                + Delete(PhotosensorFactory*)
                + Make(PhotosensorFactory, int): Photosensor
            }

            Photosensor <- PhotosensorFactory
        }

        folder temperature_sensors {
            interface TemperatureSensor {
                + Delete(TemperatureSensor*)
                + SensorWatchCommand(Sensor, const char*, Command): Command
                + GetId(Sensor): int
                + GetTag(Sensor): const char*
                + GetState(Sensor): const char*
                + IsNormal(Sensor): bool
            }

            interface TemperatureSensorFactory {
                + Delete(TemperatureSensorFactory*)
                + Make(TemperatureSensorFactory, int): TemperatureSensor
            }

            TemperatureSensor <- TemperatureSensorFactory
        }

        Sensor <- SensorFactory
        Sensor <|.. Microswitch
        Sensor <|.. Photosensor
        Sensor <|.. TemperatureSensor
    }

    Command <|-- Sensor
}
@enduml
