@startuml sensor_class_diagram
skinparam {
    defaultFontName Ricty Diminished
    monochrome true
}

package Golem {
    interface Component

    folder sensors {
        interface Sensor {
            + Delete(Component*)
            + Id(Component): int
            + Tag(Component): const char*
            + State(Component): const char*
            + IsDefaultState(Component): bool
        }

        interface NullSensor {
            + GetInstance(): Component
        }

        folder microswitches {
            interface Microswitch {
                + Delete(Component*)
                + Id(Component): int
                + Tag(Component): const char*
                + State(Component): const char*
                + IsOff(Component): bool
                + IsOn(Component): bool
            }

            interface NullMicroswitch {
                + GetInstance(): Component
            }

            Microswitch <|-- NullMicroswitch
        }

        folder photosensors {
            interface Photosensor {
                + Delete(Component*)
                + Id(Component): int
                + Tag(Component): const char*
                + State(Component): const char*
                + IsLight(Component): bool
                + IsDark(Component): bool
            }

            interface NullPhotosensor {
                + GetInstance(): Component
            }

            Photosensor <|-- NullPhotosensor
        }

        folder temperature_sensors {
            interface TemperatureSensor {
                + Delete(Component*)
                + Id(Component): int
                + Tag(Component): const char*
                + State(Component): const char*
                + IsNormal(Component): bool
            }

            interface NullTemperatureSensor {
                + GetInstance(): Component
            }

            TemperatureSensor <|-- NullTemperatureSensor
        }

        Sensor <|-- NullSensor
        Sensor <|.. Microswitch
        Sensor <|.. Photosensor
        Sensor <|.. TemperatureSensor
    }

    Component <|.. Sensor
}
@enduml
